stages:
  - build
  - docker-build
  - docker-push

job 1:
  stage: build
  script: "echo 'This is docker build'"

job 2:
  stage: docker-build
  script: "echo 'This is docker-build'"

job 3:
  stage: docker-push
  script: "echo 'This is docker build-push'"
