stages:
  - build
  - test

job-build:
  stage: build
  image: golang
  script: ./build.sh

job-test:
  stage: test

#  script: "curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh; dep ensure; export CGO_ENABLED=0 GOOS=linux GOARCH=amd64; go build -o istio-tester;"


