stages:
  - build
  - test

job-build:
  stage: build
  image: golang
  script: ./build.sh
  artifacts:
    paths:
    - istio-teste-new-build
    expire_in: 1 day

job-test:
  stage: test
  image: golang
  dependencies:
    - job-build
  script: ls -all



#  script: "curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh; dep ensure; export CGO_ENABLED=0 GOOS=linux GOARCH=amd64; go build -o istio-tester;"


