version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/istio-tester
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh;
      - run: dep ensure
      - run: go build -o istio-teste-new-build;
      - run: ls -all
      - store_artifacts:
          path: istio-teste-new-build
  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/istio-tester
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh;
      - run: dep ensure
      - run: go test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build